### ISSUE TITLE
[BUG] - event fout bij upgrade datepicker

### ISSUE THREAD

**Issue by SBylemans** [milieuinfo/webcomponent-vl-ui-datepicker#159]
**Omschrijf het probleem**
Na update datepicker, wordt volgende fout in console getoond:
![image](https://user-images.githubusercontent.com/5698858/117326239-c4317a80-ae91-11eb-929c-ffd0c235d1db.png)

**Hoe te reproduceren**
Datum selecteren in demo pagina heeft zelfde fout als in screenshot.

**Gewenst gedrag**
Geen fout

**Comment by driesva** [comment]
Ik zie deze fout ook na upgrade naar vl-ui-bom versie 3.1.0 en onze frontend unit testen lijken hierdoor te falen
```
      ReferenceError: e is not defined
        at equalDates (node_modules/vl-ui-datepicker/lib/datepicker.js:2827:26)
        at HTMLInputElement.<anonymous> (node_modules/vl-ui-datepicker/lib/datepicker.js:2835:69)
        at triggerEvent (node_modules/vl-ui-datepicker/lib/datepicker.js:2477:24)
        at Object.setDate (node_modules/vl-ui-datepicker/lib/datepicker.js:2363:30)
        at HTMLElement.set value [as value] (node_modules/vl-ui-datepicker/dist/vl-datepicker.src.js:99:23)
```

```
  "name": "vl-ui-datepicker",
  "version": "3.2.6",
```

Ook nog aanwezig in versie 3.2.7, maar niet in 3.2.5. Oorzaak is waarschijnlijk #156, ik bekijk het eerst eens zelf.

**Comment by driesva** [comment]
@coemans fout zit blijkbaar in lib/datepicker.js 

Dit is niet van ons maar komt van AIV? Dus daar moet PR worden geopend?
